### ISSUE TITLE
Register logs not shown in the syslog

### ISSUE THREAD

**Issue by balaji07s** [os11k/sipp2freeswitch#1]
Hi @os11k,

      When I try to connect my sip phone to the kamailio sip server the register messages are shown in the logs when i checked the logs there are no logs regarding register packets but when I tried using tcpdump to listen on that port there was packet exchange between between sip server and sip softphone. The registrar.so module also is enabled in the config file. please share anything I can to do get those register messages shown in the kamailio logs.

Thanks

**Comment by os11k** [comment]
Hi @balaji07s 

I don't really understand what you are doing and what you want to achieve and what do not works. Could you please explain?

**Comment by balaji07s** [comment]
hi @os11k 
     I am working on a voip based project and i have installed kamailio v5.5.2 as my sip proxy and sip register. It was installed properly and i can able to make calls and the INVITE, BYE messages are showing in the kamailio logs properly and also inserted into the database successfully. But i also need to show the REGISTER and SUBSCRIBE messages to the database and even though the dialog module is loaded it is still not showing anything on the logs or on siremis webpage like a call in progress. I also tried to debug them and also searched on the internet but didn't get anything relevant to this can you please help me out on this three issues i am facing.

These are the errors i am getting while register from softphone.

Nov 08 15:40:52 balaji-VirtualBox /usr/sbin/kamailio[12886]: ERROR: <core> [db_query.c:244]: db_do_insert_cmd(): error while submitting query
Nov 08 15:40:52 balaji-VirtualBox /usr/sbin/kamailio[12886]: ERROR: usrloc [ucontact.c:687]: db_insert_ucontact(): inserting contact in db failed 123 (uloc-6188f6f8-324c-1)
Nov 08 15:40:52 balaji-VirtualBox /usr/sbin/kamailio[12886]: ERROR: usrloc [urecord.c:420]: wb_timer(): inserting contact into database failed (aor: 123)
Nov 08 15:42:55 balaji-VirtualBox /usr/sbin/kamailio[12888]: INFO: {1 2 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:44:16 balaji-VirtualBox /usr/sbin/kamailio[12889]: INFO: {1 4 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:45:37 balaji-VirtualBox /usr/sbin/kamailio[12891]: INFO: {1 5 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:46:58 balaji-VirtualBox /usr/sbin/kamailio[12892]: INFO: {1 6 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:48:19 balaji-VirtualBox /usr/sbin/kamailio[12893]: INFO: {1 8 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:49:40 balaji-VirtualBox /usr/sbin/kamailio[12895]: INFO: {1 9 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:52:22 balaji-VirtualBox /usr/sbin/kamailio[12890]: INFO: {1 11 REGISTER tYSdLZwJ4bflnJg57bYX1A..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed


Thank you

**Comment by os11k** [comment]
Hi @balaji07s ,

I'm sorry but this is nothing to do with sipp scripts in this repository. I'm closing this issue. Please contact Kamailio mailing list if you need more help.
